# Generated by Django 6.0.6 on 2026-08-29 08:09
#
# DESTRUCTIVE: this actually drops the purchases_category table and the
# product.category_id column — not a state-only relabel like the earlier
# `inventory` app extraction. Any existing Category rows and every
# Product.category assignment are permanently lost when this runs against a
# populated database. Product is now capped at exactly 4 fixed rows (Jumbo,
# Cores, Packing, Cartons — seeded by seed_fixed_products) with no category
# concept at all; the 6 new Jumbo/Core/Packing/Carton attribute lookups
# replace what Category used to be used for. Review before applying against
# any database that isn't confirmed-local-throwaway, per
# instructions/database-safety.md.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0020_iexact_uniqueness_check_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
