# Generated by Django 6.0.6 on 2026-08-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0023_corename_delete_jumbobinding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostinventoryfifoconsumption',
            name='quantity',
            field=models.DecimalField(decimal_places=4, help_text='Quantity originally drawn from this batch when marked lost.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='lostinventoryfifoconsumption',
            name='restored_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='lostinventoryitem',
            name='found_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='lostinventoryitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='lostinventoryrecovery',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='remaining_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='returned_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='purchaseitemshelfallocation',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='purchasereturnitemshelfallocation',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
    ]
