# Generated by Django 6.0.6 on 2026-08-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0025_product_variant_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='exact_length_m',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='expected_length_m',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='freight_cost',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='rate_per_kg',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
    ]
