# Generated by Django 6.0.6 on 2026-09-05 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_fgproduct_trigram_search_index'),
        ('purchases', '0026_purchaseitem_exact_length_m_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lostinventoryitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lostinventoryfifoconsumption',
            name='cutting_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lost_inventory_consumptions', to='production.cuttingbreakdownitem'),
        ),
        migrations.AddField(
            model_name='lostinventoryfifoconsumption',
            name='fg_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lost_inventory_consumptions', to='production.packingoutputitem'),
        ),
        migrations.AddField(
            model_name='lostinventoryfifoconsumption',
            name='rewinding_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lost_inventory_consumptions', to='production.recipebreakdownitem'),
        ),
        migrations.AddField(
            model_name='lostinventoryitem',
            name='fg_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lost_inventory_items', to='production.fgproduct'),
        ),
        migrations.AddField(
            model_name='lostinventoryitem',
            name='rm_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lost_inventory_items', to='purchases.product'),
        ),
        migrations.AddField(
            model_name='lostinventoryitem',
            name='type',
            field=models.CharField(choices=[('raw_material', 'Raw Material'), ('wip_core', 'WIP Core'), ('wip_piece', 'WIP Piece'), ('finished_goods', 'Finished Goods')], db_index=True, default='raw_material', max_length=20),
        ),
        migrations.AddField(
            model_name='lostinventoryitem',
            name='wip_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lost_inventory_items', to='production.wipproduct'),
        ),
        migrations.AlterField(
            model_name='lostinventoryfifoconsumption',
            name='purchase_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lost_inventory_consumptions', to='purchases.purchaseitem'),
        ),
        migrations.AddConstraint(
            model_name='lostinventoryfifoconsumption',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('purchase_item__isnull', False), ('rewinding_batch__isnull', True), ('cutting_batch__isnull', True), ('fg_batch__isnull', True)), models.Q(('purchase_item__isnull', True), ('rewinding_batch__isnull', False), ('cutting_batch__isnull', True), ('fg_batch__isnull', True)), models.Q(('purchase_item__isnull', True), ('rewinding_batch__isnull', True), ('cutting_batch__isnull', False), ('fg_batch__isnull', True)), models.Q(('purchase_item__isnull', True), ('rewinding_batch__isnull', True), ('cutting_batch__isnull', True), ('fg_batch__isnull', False)), _connector='OR'), name='lostinvfifoconsumption_exactly_one_batch_fk'),
        ),
        migrations.AddConstraint(
            model_name='lostinventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rm_product__isnull', False), ('wip_product__isnull', True), ('fg_product__isnull', True)), models.Q(('rm_product__isnull', True), ('wip_product__isnull', False), ('fg_product__isnull', True)), models.Q(('rm_product__isnull', True), ('wip_product__isnull', True), ('fg_product__isnull', False)), _connector='OR'), name='lostinventoryitem_exactly_one_product_fk'),
        ),
        migrations.AddConstraint(
            model_name='lostinventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('rm_product__isnull', False)), fields=('record', 'rm_product'), name='lostinventoryitem_unique_rm_per_record'),
        ),
        migrations.AddConstraint(
            model_name='lostinventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('wip_product__isnull', False)), fields=('record', 'wip_product'), name='lostinventoryitem_unique_wip_per_record'),
        ),
        migrations.AddConstraint(
            model_name='lostinventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('fg_product__isnull', False)), fields=('record', 'fg_product'), name='lostinventoryitem_unique_fg_per_record'),
        ),
        migrations.RemoveField(
            model_name='lostinventoryitem',
            name='product',
        ),
    ]
