# Generated by Django 6.0.6 on 2026-09-10 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_payment_method'),
        ('production', '0014_recipe_labor_machine_and_full_cost'),
        ('purchases', '0027_alter_lostinventoryitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoiceitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fifoledger',
            name='fg_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fifo_consumed', to='production.packingoutputitem'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='fg_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='production.fgproduct'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='rm_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='purchases.product'),
        ),
        migrations.AlterField(
            model_name='fifoledger',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fifo_consumed', to='purchases.purchaseitem'),
        ),
        migrations.AddConstraint(
            model_name='fifoledger',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('purchase__isnull', False), ('fg_batch__isnull', True)), models.Q(('purchase__isnull', True), ('fg_batch__isnull', False)), _connector='OR'), name='fifoledger_exactly_one_batch'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rm_product__isnull', False), ('fg_product__isnull', True)), models.Q(('rm_product__isnull', True), ('fg_product__isnull', False)), _connector='OR'), name='invoiceitem_exactly_one_product'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.UniqueConstraint(condition=models.Q(('rm_product__isnull', False)), fields=('invoice', 'rm_product'), name='uniq_invoiceitem_invoice_rm_product'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.UniqueConstraint(condition=models.Q(('fg_product__isnull', False)), fields=('invoice', 'fg_product'), name='uniq_invoiceitem_invoice_fg_product'),
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product',
        ),
    ]
