# Generated by Django 6.0.6 on 2026-09-20 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_fg_selling_cartons'),
    ]

    operations = [
        migrations.AddField(
            model_name='fifoledger',
            name='reverses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_entries', to='billing.fifoledger'),
        ),
    ]
