# Generated by Django 6.0.6 on 2026-09-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_balancesheetsnapshot_asset_revaluation_surplus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheetsnapshot',
            name='dl_foh_payable',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Accrued-minus-paid DL/FOH — see manufacturing_costs.selectors.get_dl_foh_payable_balance.', max_digits=20),
        ),
    ]
