# Generated by Django 6.0.6 on 2026-08-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.DecimalField(db_index=True, decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='productstockmovement',
            name='total_found',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='productstockmovement',
            name='total_lost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='productstockmovement',
            name='total_purchase_returned',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='productstockmovement',
            name='total_purchased',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='productstockmovement',
            name='total_sale_returned',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='productstockmovement',
            name='total_sold',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='shelfstock',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='shelfstockmovement',
            name='delta',
            field=models.DecimalField(decimal_places=4, help_text='Positive = added to shelf, negative = removed from shelf.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='stockmovementflow',
            name='total_found',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='stockmovementflow',
            name='total_lost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='stockmovementflow',
            name='total_purchase_returned',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='stockmovementflow',
            name='total_purchased',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='stockmovementflow',
            name='total_sale_returned',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='stockmovementflow',
            name='total_sold',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
    ]
