# Generated by Django 6.0.6 on 2026-08-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_jumbo_length_correction_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfstockmovement',
            name='reason',
            field=models.CharField(choices=[('purchase_putaway', 'Purchase Put-Away'), ('sale_consumption', 'Sale Consumption'), ('invoice_return_putaway', 'Invoice Return Put-Away'), ('purchase_return_consumption', 'Purchase Return Consumption'), ('lost_consumption', 'Lost Inventory Consumption'), ('lost_found_putaway', 'Lost Inventory Found Put-Away'), ('move_out', 'Manual Move (Out)'), ('move_in', 'Manual Move (In)'), ('jumbo_length_correction', 'Jumbo Exact-Length Correction'), ('recipe_issue_consumption', 'Recipe Material Issue'), ('backfill', 'Backfill')], db_index=True, max_length=30),
        ),
    ]
