# Generated by Django 6.0.6 on 2026-09-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_add_wip_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='WipInventoryStatsFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('total_stock', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('low_stock_count', models.PositiveIntegerField(default=0)),
                ('out_of_stock_count', models.PositiveIntegerField(default=0)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WIP Inventory Stats Flow',
                'verbose_name_plural': 'WIP Inventory Stats Flow',
            },
        ),
        migrations.AddField(
            model_name='inventorystatsflow',
            name='total_stock',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
