# Generated by Django 6.0.6 on 2026-09-05 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_wipinventorystatsflow_inventorystatsflow_total_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FgInventoryStatsFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('total_stock', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('low_stock_count', models.PositiveIntegerField(default=0)),
                ('out_of_stock_count', models.PositiveIntegerField(default=0)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FG Inventory Stats Flow',
                'verbose_name_plural': 'FG Inventory Stats Flow',
            },
        ),
        migrations.CreateModel(
            name='FgShelfStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FG Shelf Stock',
                'verbose_name_plural': 'FG Shelf Stock',
            },
        ),
        migrations.CreateModel(
            name='FgShelfStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.DecimalField(decimal_places=4, help_text='Positive = added to shelf, negative = removed from shelf.', max_digits=14)),
                ('reason', models.CharField(choices=[('packing_output_putaway', 'Packing Output Put-Away')], db_index=True, max_length=30)),
                ('reference', models.CharField(blank=True, default='', help_text='e.g. PAK-2026-0001', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'FG Shelf Stock Movement',
                'verbose_name_plural': 'FG Shelf Stock Movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='wipshelfstockmovement',
            name='reason',
            field=models.CharField(choices=[('recipe_breakdown_putaway', 'Recipe Breakdown Put-Away'), ('cutting_issue_consumption', 'Cutting Issue Consumption'), ('cutting_breakdown_putaway', 'Cutting Breakdown Put-Away'), ('packing_issue_consumption', 'Packing Issue Consumption')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='FgInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(db_index=True, decimal_places=4, default=0, max_digits=14)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fg_inventory_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FG Inventory',
                'verbose_name_plural': 'FG Inventories',
                'ordering': ['product__name'],
            },
        ),
    ]
