# Generated by Django 6.0.6 on 2026-09-05 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_fginventorystatsflow_fgshelfstock_and_more'),
        ('production', '0010_wipproduct_code_alter_recipe_recipe_type_fgproduct_and_more'),
        ('purchases', '0026_purchaseitem_exact_length_m_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fginventory',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='production.fgproduct'),
        ),
        migrations.AddField(
            model_name='fgshelfstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shelf_stock_rows', to='production.fgproduct'),
        ),
        migrations.AddField(
            model_name='fgshelfstock',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fg_stock_rows', to='purchases.shelf'),
        ),
        migrations.AddField(
            model_name='fgshelfstockmovement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fg_shelf_stock_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fgshelfstockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shelf_movements', to='production.fgproduct'),
        ),
        migrations.AddField(
            model_name='fgshelfstockmovement',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fg_movements', to='purchases.shelf'),
        ),
        migrations.AlterUniqueTogether(
            name='fgshelfstock',
            unique_together={('shelf', 'product')},
        ),
    ]
