# Generated by Django 6.0.6 on 2026-09-05 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_fginventory_product_fgshelfstock_product_and_more'),
        ('production', '0013_fgproduct_trigram_search_index'),
        ('purchases', '0026_purchaseitem_exact_length_m_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRegistryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('raw_material', 'Raw Material'), ('wip_core', 'WIP Core'), ('wip_piece', 'WIP Piece'), ('finished_goods', 'Finished Goods')], db_index=True, max_length=20)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('fg_product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registry_entry', to='production.fgproduct')),
                ('rm_product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registry_entry', to='purchases.product')),
                ('wip_product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registry_entry', to='production.wipproduct')),
            ],
            options={
                'verbose_name': 'Product Registry Entry',
                'verbose_name_plural': 'Product Registry Entries',
                'indexes': [models.Index(fields=['type', 'name'], name='inventory_p_type_9904c3_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('rm_product__isnull', False), ('wip_product__isnull', True), ('fg_product__isnull', True)), models.Q(('rm_product__isnull', True), ('wip_product__isnull', False), ('fg_product__isnull', True)), models.Q(('rm_product__isnull', True), ('wip_product__isnull', True), ('fg_product__isnull', False)), _connector='OR'), name='registry_exactly_one_product_fk')],
            },
        ),
    ]
