# Generated by Django 6.0.6 on 2026-09-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_productregistryentry_trigram_search_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fgshelfstockmovement',
            name='reason',
            field=models.CharField(choices=[('packing_output_putaway', 'Packing Output Put-Away'), ('lost_consumption', 'Lost Inventory Consumption'), ('lost_found_putaway', 'Lost Inventory Found Put-Away'), ('sale_consumption', 'Sale Consumption'), ('invoice_return_putaway', 'Invoice Return Put-Away')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='wipshelfstockmovement',
            name='reason',
            field=models.CharField(choices=[('recipe_breakdown_putaway', 'Recipe Breakdown Put-Away'), ('cutting_issue_consumption', 'Cutting Issue Consumption'), ('cutting_breakdown_putaway', 'Cutting Breakdown Put-Away'), ('packing_issue_consumption', 'Packing Issue Consumption'), ('lost_consumption', 'Lost Inventory Consumption'), ('lost_found_putaway', 'Lost Inventory Found Put-Away')], db_index=True, max_length=30),
        ),
    ]
