# Generated by Django 6.0.6 on 2026-09-11 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_fg_selling_cartons'),
        ('production', '0014_recipe_labor_machine_and_full_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovementflow',
            name='total_fg_sale_returned',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='stockmovementflow',
            name='total_fg_sold',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='FgProductStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sold', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('total_sale_returned', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('fg_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movement', to='production.fgproduct')),
            ],
            options={
                'verbose_name': 'FG Product Stock Movement',
                'verbose_name_plural': 'FG Product Stock Movement',
            },
        ),
    ]
