# Generated by Django 6.0.6 on 2026-09-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_stockmovementflow_total_fg_sale_returned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fginventory',
            name='avg_unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='inventory',
            name='avg_unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='wipinventory',
            name='avg_unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
    ]
