# Generated by Django 6.0.6 on 2026-09-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profits', '0004_profitflow_total_paid_out_to_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyprofit',
            name='direct_labor_paid',
            field=models.DecimalField(decimal_places=4, default=0, help_text='manufacturing_costs.Payment against Employee entities, dated this month.', max_digits=20),
        ),
        migrations.AddField(
            model_name='monthlyprofit',
            name='factory_overhead_paid',
            field=models.DecimalField(decimal_places=4, default=0, help_text='manufacturing_costs.Payment against Machine/Rent/Electricity entities, dated this month.', max_digits=20),
        ),
    ]
