# Generated by Django 6.0.6 on 2026-09-08 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingCostsFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshots_caught_up_through', models.CharField(blank=True, help_text='YYYY-MM', max_length=7, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manufacturing Costs Flow',
                'verbose_name_plural': 'Manufacturing Costs Flow',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('monthly_salary', models.DecimalField(decimal_places=4, max_digits=14)),
                ('avg_hours_per_day', models.DecimalField(decimal_places=2, max_digits=6)),
                ('working_days_per_month', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rate_per_hour', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mfg_employees_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mfg_employees_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mfg_employees_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FactoryOverheadSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('electricity_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mfg_foh_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factory Overhead Setting',
                'verbose_name_plural': 'Factory Overhead Setting',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('rewinding', 'Rewinding'), ('cutting', 'Cutting'), ('packing', 'Packing')], db_index=True, max_length=20)),
                ('avg_hours_per_day', models.DecimalField(decimal_places=2, max_digits=6)),
                ('working_days_per_month', models.DecimalField(decimal_places=2, max_digits=6)),
                ('monthly_repair_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('rate_per_hour', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mfg_machines_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mfg_machines_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mfg_machines_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PayableEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('employee', 'Employee'), ('machine', 'Machine'), ('rent', 'Rent'), ('electricity', 'Electricity')], db_index=True, max_length=20)),
                ('overall_total_paid', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('overall_payment_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mfg_payable_entities_deleted', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payable_entity', to='manufacturing_costs.employee')),
                ('machine', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payable_entity', to='manufacturing_costs.machine')),
            ],
            options={
                'verbose_name': 'Payable Entity',
                'verbose_name_plural': 'Payable Entities',
            },
        ),
        migrations.CreateModel(
            name='PayableEntityMonthlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(db_index=True, help_text='YYYY-MM', max_length=7)),
                ('total_paid', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_snapshots', to='manufacturing_costs.payableentity')),
            ],
            options={
                'verbose_name': 'Payable Entity Monthly Snapshot',
                'verbose_name_plural': 'Payable Entity Monthly Snapshots',
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('payment_date', models.DateField(db_index=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mfg_payments_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mfg_payments_deleted', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='manufacturing_costs.payableentity')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mfg_payments_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='payableentity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'employee'), ('employee__isnull', False), ('machine__isnull', True)), models.Q(('type', 'machine'), ('employee__isnull', True), ('machine__isnull', False)), models.Q(('type__in', ['rent', 'electricity']), ('employee__isnull', True), ('machine__isnull', True)), _connector='OR'), name='payableentity_type_matches_source'),
        ),
        migrations.AddConstraint(
            model_name='payableentity',
            constraint=models.UniqueConstraint(condition=models.Q(('type__in', ['rent', 'electricity'])), fields=('type',), name='payableentity_singleton_rent_electricity'),
        ),
        migrations.AddConstraint(
            model_name='payableentitymonthlysnapshot',
            constraint=models.UniqueConstraint(fields=('entity', 'period'), name='uniq_payable_entity_snapshot_period'),
        ),
    ]
