# Generated by Django 6.0.6 on 2026-09-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_costs', '0002_trigram_search_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingCostsStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_employees', models.PositiveIntegerField(default=0)),
                ('total_machines', models.PositiveIntegerField(default=0)),
                ('total_estimated_monthly_dl', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total_estimated_monthly_foh', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('last_month_dl_paid', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('last_month_foh_paid', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manufacturing Costs Stats',
                'verbose_name_plural': 'Manufacturing Costs Stats',
            },
        ),
    ]
