# Generated by Django 6.0.6 on 2026-09-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_costs', '0003_manufacturing_costs_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingcostsstats',
            name='this_month_dl_paid',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='manufacturingcostsstats',
            name='this_month_foh_paid',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='manufacturingcostsstats',
            name='this_month_period',
            field=models.CharField(blank=True, help_text='YYYY-MM', max_length=7, null=True),
        ),
    ]
