# Generated by Django 6.0.6 on 2026-09-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_costs', '0004_this_month_dl_foh_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingcostsstats',
            name='total_dl_foh_accrued',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
