# Generated by Django 6.0.6 on 2026-09-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0011_cashmovement_opening_cash_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='total_direct_labor_paid',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Total ever paid to manufacturing_costs.Employee rows (Direct Labor), all-time. Only ever increases.', max_digits=20),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='total_factory_overhead_paid',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Total ever paid against manufacturing_costs.PayableEntity rows of type machine/rent/electricity (Factory Overhead), all-time. Only ever increases.', max_digits=20),
        ),
    ]
