# Generated by Django 6.0.6 on 2026-08-30 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0026_purchaseitem_exact_length_m_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('recipe_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('recipe_type', models.CharField(choices=[('rewinding', 'Rewinding')], db_index=True, default='rewinding', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('under_processing', 'Under Processing'), ('finished', 'Finished')], db_index=True, default='under_processing', max_length=20)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=14, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('finished_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_recipes', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIssuedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('jumbo', 'Jumbo'), ('cores', 'Cores')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_issuances', to='purchases.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_materials', to='production.recipe')),
            ],
            options={
                'verbose_name': 'Recipe Issued Material',
                'verbose_name_plural': 'Recipe Issued Materials',
                'unique_together': {('recipe', 'kind')},
            },
        ),
        migrations.CreateModel(
            name='RecipeMaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='production.recipeissuedmaterial')),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_consumptions', to='purchases.purchaseitem')),
            ],
            options={
                'verbose_name': 'Recipe Material Consumption',
                'verbose_name_plural': 'Recipe Material Consumptions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewoundCoreBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('value', models.CharField(max_length=255, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rewound Core Binding',
                'verbose_name_plural': 'Rewound Core Bindings',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='RewoundCoreLengthMm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('value', models.DecimalField(decimal_places=4, max_digits=14, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rewound Core Length (mm)',
                'verbose_name_plural': 'Rewound Core Lengths (mm)',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='RewoundCoreYard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('value', models.DecimalField(decimal_places=4, max_digits=14, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rewound Core Yard',
                'verbose_name_plural': 'Rewound Core Yards',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='WipProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('variant_key', models.CharField(editable=False, max_length=500, unique=True)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wip_products', to='production.rewoundcorebinding')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wip_products', to='purchases.family')),
                ('length_mm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wip_products', to='production.rewoundcorelengthmm')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('yard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wip_products', to='production.rewoundcoreyard')),
            ],
            options={
                'verbose_name': 'WIP Product',
                'verbose_name_plural': 'WIP Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WipInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(db_index=True, decimal_places=4, default=0, max_digits=14)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wip_inventory_updates', to=settings.AUTH_USER_MODEL)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='production.wipproduct')),
            ],
            options={
                'verbose_name': 'WIP Inventory',
                'verbose_name_plural': 'WIP Inventories',
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeBreakdownItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('remaining_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('unit_cost_snapshot', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown_items', to='production.recipe')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('wip_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breakdown_items', to='production.wipproduct')),
            ],
            options={
                'verbose_name': 'Recipe Breakdown Item',
                'verbose_name_plural': 'Recipe Breakdown Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WipShelfStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.DecimalField(decimal_places=4, help_text='Positive = added to shelf, negative = removed from shelf.', max_digits=14)),
                ('reason', models.CharField(choices=[('recipe_breakdown_putaway', 'Recipe Breakdown Put-Away')], db_index=True, max_length=30)),
                ('reference', models.CharField(blank=True, default='', help_text='e.g. REC-2026-0001', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wip_shelf_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shelf_movements', to='production.wipproduct')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wip_movements', to='purchases.shelf')),
            ],
            options={
                'verbose_name': 'WIP Shelf Stock Movement',
                'verbose_name_plural': 'WIP Shelf Stock Movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WipShelfStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shelf_stock_rows', to='production.wipproduct')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wip_stock_rows', to='purchases.shelf')),
            ],
            options={
                'verbose_name': 'WIP Shelf Stock',
                'verbose_name_plural': 'WIP Shelf Stock',
                'unique_together': {('shelf', 'product')},
            },
        ),
    ]
