# Generated by Django 6.0.6 on 2026-08-30 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_trigram_search_indexes'),
        ('purchases', '0026_purchaseitem_exact_length_m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='RecipeMaterialShelfDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('draw', 'Drawn From'), ('return', 'Returned To')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_draws', to='production.recipeissuedmaterial')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_material_draws', to='purchases.shelf')),
            ],
            options={
                'verbose_name': 'Recipe Material Shelf Draw',
                'verbose_name_plural': 'Recipe Material Shelf Draws',
                'ordering': ['created_at'],
            },
        ),
    ]
