# Generated by Django 6.0.6 on 2026-08-30 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_recipe_description_optional_and_shelf_draw'),
        ('purchases', '0026_purchaseitem_exact_length_m_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeBreakdownItemShelfAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('breakdown_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_allocations', to='production.recipebreakdownitem')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_breakdown_allocations', to='purchases.shelf')),
            ],
            options={
                'verbose_name': 'Recipe Breakdown Item Shelf Allocation',
                'verbose_name_plural': 'Recipe Breakdown Item Shelf Allocations',
                'unique_together': {('breakdown_item', 'shelf')},
            },
        ),
    ]
