# Generated by Django 6.0.6 on 2026-09-05 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_recipe_breakdown_item_shelf_allocation'),
        ('purchases', '0026_purchaseitem_exact_length_m_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='waste_cost',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='waste_length_mm',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='wipproduct',
            name='stage',
            field=models.CharField(choices=[('rewinding', 'Rewinding'), ('cutting', 'Cutting')], db_index=True, default='rewinding', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('rewinding', 'Rewinding'), ('cutting', 'Cutting')], db_index=True, default='rewinding', max_length=20),
        ),
        migrations.CreateModel(
            name='CuttingBreakdownItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('length_mm', models.DecimalField(decimal_places=4, max_digits=14)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('remaining_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('unit_cost_before_waste', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('unit_cost_snapshot', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_breakdown_items', to='production.recipe')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('wip_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cutting_breakdown_items', to='production.wipproduct')),
            ],
            options={
                'verbose_name': 'Cutting Breakdown Item',
                'verbose_name_plural': 'Cutting Breakdown Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CuttingIssuedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_issued_material', to='production.recipe')),
                ('wip_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cutting_issuances', to='production.wipproduct')),
            ],
            options={
                'verbose_name': 'Cutting Issued Material',
                'verbose_name_plural': 'Cutting Issued Materials',
            },
        ),
        migrations.CreateModel(
            name='CuttingMaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='production.cuttingissuedmaterial')),
                ('wip_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cutting_consumptions', to='production.recipebreakdownitem')),
            ],
            options={
                'verbose_name': 'Cutting Material Consumption',
                'verbose_name_plural': 'Cutting Material Consumptions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CuttingMaterialShelfDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('draw', 'Drawn From'), ('return', 'Returned To')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_draws', to='production.cuttingissuedmaterial')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cutting_material_draws', to='purchases.shelf')),
            ],
            options={
                'verbose_name': 'Cutting Material Shelf Draw',
                'verbose_name_plural': 'Cutting Material Shelf Draws',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CuttingBreakdownItemShelfAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('breakdown_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_allocations', to='production.cuttingbreakdownitem')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cutting_breakdown_allocations', to='purchases.shelf')),
            ],
            options={
                'verbose_name': 'Cutting Breakdown Item Shelf Allocation',
                'verbose_name_plural': 'Cutting Breakdown Item Shelf Allocations',
                'unique_together': {('breakdown_item', 'shelf')},
            },
        ),
    ]
