# Generated by Django 6.0.6 on 2026-09-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_backfill_wipproduct_variant_key_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='finished_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='wipshelfstockmovement',
            name='reason',
            field=models.CharField(choices=[('recipe_breakdown_putaway', 'Recipe Breakdown Put-Away'), ('cutting_issue_consumption', 'Cutting Issue Consumption'), ('cutting_breakdown_putaway', 'Cutting Breakdown Put-Away')], db_index=True, max_length=30),
        ),
    ]
