# Generated by Django 6.0.6 on 2026-09-05 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_remove_wip_models_state_only'),
        ('purchases', '0026_purchaseitem_exact_length_m_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wipproduct',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('rewinding', 'Rewinding'), ('cutting', 'Cutting'), ('packing', 'Packing')], db_index=True, default='rewinding', max_length=20),
        ),
        migrations.CreateModel(
            name='FgProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(editable=False, max_length=30, unique=True)),
                ('variant_key', models.CharField(editable=False, max_length=500, unique=True)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fg_products', to='production.rewoundcorebinding')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('length_mm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fg_products', to='production.rewoundcorelengthmm')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('yard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fg_products', to='production.rewoundcoreyard')),
            ],
            options={
                'verbose_name': 'FG Product',
                'verbose_name_plural': 'FG Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackingIssuedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_issuances', to='purchases.product')),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packing_issued_material', to='production.recipe')),
            ],
            options={
                'verbose_name': 'Packing Issued Material',
                'verbose_name_plural': 'Packing Issued Materials',
            },
        ),
        migrations.CreateModel(
            name='PackingIssuedPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packing_issued_piece', to='production.recipe')),
                ('wip_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_issuances', to='production.wipproduct')),
            ],
            options={
                'verbose_name': 'Packing Issued Piece',
                'verbose_name_plural': 'Packing Issued Pieces',
            },
        ),
        migrations.CreateModel(
            name='PackingMaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='production.packingissuedmaterial')),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_consumptions', to='purchases.purchaseitem')),
            ],
            options={
                'verbose_name': 'Packing Material Consumption',
                'verbose_name_plural': 'Packing Material Consumptions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackingMaterialShelfDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('draw', 'Drawn From'), ('return', 'Returned To')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_draws', to='production.packingissuedmaterial')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_material_draws', to='purchases.shelf')),
            ],
            options={
                'verbose_name': 'Packing Material Shelf Draw',
                'verbose_name_plural': 'Packing Material Shelf Draws',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackingOutputItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('remaining_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('unit_cost_snapshot', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('fg_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_output_items', to='production.fgproduct')),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packing_output_item', to='production.recipe')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Packing Output Item',
                'verbose_name_plural': 'Packing Output Items',
            },
        ),
        migrations.CreateModel(
            name='PackingPieceConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='production.packingissuedpiece')),
                ('piece_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_consumptions', to='production.cuttingbreakdownitem')),
            ],
            options={
                'verbose_name': 'Packing Piece Consumption',
                'verbose_name_plural': 'Packing Piece Consumptions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackingPieceShelfDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('draw', 'Drawn From'), ('return', 'Returned To')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_draws', to='production.packingissuedpiece')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_piece_draws', to='purchases.shelf')),
            ],
            options={
                'verbose_name': 'Packing Piece Shelf Draw',
                'verbose_name_plural': 'Packing Piece Shelf Draws',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackingOutputShelfAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('output_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_allocations', to='production.packingoutputitem')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_output_allocations', to='purchases.shelf')),
            ],
            options={
                'verbose_name': 'Packing Output Shelf Allocation',
                'verbose_name_plural': 'Packing Output Shelf Allocations',
                'unique_together': {('output_item', 'shelf')},
            },
        ),
    ]
