# Generated by Django 6.0.6 on 2026-09-09 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_costs', '0002_trigram_search_indexes'),
        ('production', '0013_fgproduct_trigram_search_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingbreakdownitem',
            name='full_unit_cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='packingoutputitem',
            name='full_unit_cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='full_cost_per_unit',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipebreakdownitem',
            name='full_unit_cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='RecipeLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_hour_snapshot', models.DecimalField(decimal_places=4, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_labor_entries', to='manufacturing_costs.employee')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_entries', to='production.recipe')),
            ],
            options={
                'verbose_name': 'Recipe Labor',
                'verbose_name_plural': 'Recipe Labor',
                'ordering': ['created_at'],
                'unique_together': {('recipe', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='RecipeMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_hour_snapshot', models.DecimalField(decimal_places=4, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_machine_entries', to='manufacturing_costs.machine')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_entries', to='production.recipe')),
            ],
            options={
                'verbose_name': 'Recipe Machine',
                'verbose_name_plural': 'Recipe Machines',
                'ordering': ['created_at'],
                'unique_together': {('recipe', 'machine')},
            },
        ),
    ]
