# Generated by Django 6.0.6 on 2026-09-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_recipe_labor_machine_and_full_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_data_entry',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
